# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-16 10:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_emailverifyrecord_group_usergroup'),
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='\u63cf\u8ff0')),
                ('max_total_time', models.IntegerField(default=7200, verbose_name='\u6700\u5927\u603b\u7b54\u9898\u65f6\u95f4\uff08\u79d2\uff09')),
                ('max_word_time', models.IntegerField(default=120, verbose_name='\u5355\u8bcd\u6700\u5927\u7b54\u9898\u65f6\u95f4\uff08\u79d2\uff09')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='\u53c2\u52a0\u6d4b\u8bd5\u7684\u5bc6\u7801')),
                ('expire_date', models.DateField(blank=True, verbose_name='\u8fc7\u671f\u65e5\u671f')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.WordBook', verbose_name='\u5355\u8bcd\u4e66')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserGroup', verbose_name='\u7fa4\u7ec4')),
            ],
            options={
                'verbose_name': '\u6d4b\u8bd5',
                'verbose_name_plural': '\u6d4b\u8bd5',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_format', models.IntegerField(choices=[(1, '\u770b\u82f1\u6587\u9009\u4e2d\u6587'), (2, '\u770b\u4e2d\u6587\u9009\u82f1\u6587'), (3, '\u62fc\u5199')], verbose_name='\u6d4b\u8bd5\u5f62\u5f0f')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Quiz', verbose_name='\u6d4b\u8bd5')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Word', verbose_name='\u5355\u8bcd')),
            ],
            options={
                'verbose_name': '\u6d4b\u8bd5\u7684\u95ee\u9898',
                'verbose_name_plural': '\u6d4b\u8bd5\u7684\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.QuizQuestion', verbose_name='\u95ee\u9898')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Quiz', verbose_name='\u6d4b\u8bd5')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6d4b\u8bd5\u7ed3\u679c',
                'verbose_name_plural': '\u6d4b\u8bd5\u7ed3\u679c',
            },
        ),
        migrations.AddField(
            model_name='quizquestionresult',
            name='quiz_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.QuizResult', verbose_name='\u6d4b\u8bd5\u7ed3\u679c'),
        ),
    ]
