# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestionresult',
            options={'verbose_name': '\u9898\u76ee\u89e3\u7b54', 'verbose_name_plural': '\u9898\u76ee\u89e3\u7b54'},
        ),
        migrations.AlterField(
            model_name='quizquestionresult',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='\u7b54\u5bf9\u4e86'),
        ),
    ]
