# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_usermessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='\u6d88\u606f\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message_type',
            field=models.IntegerField(choices=[(0, '\u7528\u6237\u6d88\u606f'), (1, '\u7533\u8bf7\u521b\u5efa\u5b66\u6821'), (2, '\u6210\u529f\u521b\u5efa\u5b66\u6821'), (3, '\u7533\u8bf7\u521b\u5efa\u73ed\u7ea7'), (4, '\u6210\u529f\u521b\u5efa\u73ed\u7ea7'), (5, '\u7533\u8bf7\u5220\u9664\u73ed\u7ea7'), (6, '\u6210\u529f\u5220\u9664\u73ed\u7ea7'), (7, '\u7533\u8bf7\u52a0\u5165\u73ed\u7ea7'), (8, '\u6210\u529f\u52a0\u5165\u73ed\u7ea7'), (9, '\u7533\u8bf7\u9000\u51fa\u73ed\u7ea7'), (10, '\u6210\u529f\u9000\u51fa\u73ed\u7ea7'), (110, '\u8bf7\u6c42\u88ab\u62d2\u7edd')], default=0, verbose_name='\u6d88\u606f\u7c7b\u578b'),
        ),
    ]
