# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20170912_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='from_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u9001\u6d88\u606f\u7684\u7528\u6237'),
        ),
    ]
