# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_group_is_admin'),
        ('learn', '0013_auto_20171116_1358'),
        ('operations', '0007_auto_20170915_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.WordBook', verbose_name='\u5355\u8bcd\u4e66')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='\u73ed\u7ea7')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7\u8bfe\u672c',
                'verbose_name_plural': '\u73ed\u7ea7\u8bfe\u672c',
            },
        ),
        migrations.CreateModel(
            name='GroupLearningPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='\u73ed\u7ea7')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.WordUnit', verbose_name='\u5355\u5143')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7\u5b66\u4e60\u8ba1\u5212',
                'verbose_name_plural': '\u73ed\u7ea7\u5b66\u4e60\u8ba1\u5212',
            },
        ),
    ]
