# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-22 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplearningplan',
            name='start_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='开始日期'),
        ),
    ]
