# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-16 10:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u5b66\u4e60\u8ba1\u5212',
                'verbose_name_plural': '\u5b66\u4e60\u8ba1\u5212',
            },
        ),
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '\u521d\u6b21\u5b66\u4e60'), (2, '\u5355\u5143\u6d4b\u8bd5'), (3, '\u590d\u4e60')], default=2, verbose_name='\u5b66\u4e60\u7c7b\u578b')),
                ('learn_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5b66\u4e60\u65f6\u95f4')),
                ('correct_rate', models.IntegerField(default=100, verbose_name='\u6b63\u786e\u7387')),
            ],
            options={
                'verbose_name': '\u5b66\u4e60\u8bb0\u5f55',
                'verbose_name_plural': '\u5b66\u4e60\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=100, verbose_name='\u62fc\u5199')),
                ('pronounciation_us', models.CharField(max_length=100, verbose_name='\u7f8e\u5f0f\u53d1\u97f3')),
                ('pronounciation_uk', models.CharField(max_length=100, verbose_name='\u82f1\u5f0f\u53d1\u97f3')),
                ('short_meaning', models.CharField(max_length=100, verbose_name='\u7b80\u5355\u89e3\u91ca')),
                ('detailed_meanings', models.TextField(blank=True, verbose_name='\u8be6\u7ec6\u89e3\u91ca')),
                ('wrong_meaning1', models.CharField(blank=True, max_length=100, verbose_name='\u9519\u8bef\u89e3\u91ca1')),
                ('wrong_meaning2', models.CharField(blank=True, max_length=100, verbose_name='\u9519\u8bef\u89e3\u91ca2')),
                ('wrong_meaning3', models.CharField(blank=True, max_length=100, verbose_name='\u9519\u8bef\u89e3\u91ca3')),
            ],
            options={
                'verbose_name': '\u5355\u8bcd',
                'verbose_name_plural': '\u5355\u8bcd',
            },
        ),
        migrations.CreateModel(
            name='WordBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='\u63cf\u8ff0')),
                ('max_word_learn_time', models.IntegerField(default=1000, verbose_name='\u6bcf\u4e2a\u5355\u8bcd\u6700\u957f\u5b66\u4e60\u79d2\u6570')),
                ('max_unit_learn_time', models.IntegerField(default=6000, verbose_name='\u6bcf\u4e2a\u5355\u5143\u6700\u957f\u5b66\u4e60\u79d2\u6570')),
                ('max_working_units', models.IntegerField(default=3, verbose_name='\u6700\u591a\u51e0\u4e2a\u5355\u5143\u540c\u65f6\u5728\u5b66\u4e60')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e0a\u4f20\u4eba')),
            ],
            options={
                'verbose_name': '\u5355\u8bcd\u4e66',
                'verbose_name_plural': '\u5355\u8bcd\u4e66',
            },
        ),
        migrations.CreateModel(
            name='WordUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='\u63cf\u8ff0')),
                ('order', models.IntegerField(default=1, verbose_name='\u987a\u5e8f')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.WordBook', verbose_name='\u5355\u8bcd\u4e66')),
            ],
            options={
                'verbose_name': '\u5355\u5143',
                'verbose_name_plural': '\u5355\u5143',
            },
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.WordUnit', verbose_name='\u5355\u5143'),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='learningplan',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.WordUnit', verbose_name='\u5355\u5143'),
        ),
        migrations.AddField(
            model_name='learningplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
