# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20170818_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='short_meaning',
            field=models.CharField(max_length=300, verbose_name='\u7b80\u5355\u89e3\u91ca'),
        ),
    ]
