# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20170818_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='mp3_uk_url',
            field=models.URLField(blank=True, verbose_name='\u82f1\u5f0f\u53d1\u97f3mp3'),
        ),
        migrations.AlterField(
            model_name='word',
            name='mp3_us_url',
            field=models.URLField(blank=True, verbose_name='\u7f8e\u5f0f\u53d1\u97f3mp3'),
        ),
    ]
