# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_wordinunit_simple_meaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pronounciation_uk',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u82f1\u5f0f\u53d1\u97f3'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronounciation_us',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u7f8e\u5f0f\u53d1\u97f3'),
        ),
    ]
