# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-19 06:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0009_auto_20170907_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_count', models.IntegerField(default=0, verbose_name='\u9519\u8bef\u6b21\u6570')),
                ('latest_error_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6700\u8fd1\u4e00\u6b21\u7b54\u9519\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.WordInUnit', verbose_name='\u5355\u8bcd')),
            ],
            options={
                'verbose_name': '\u9519\u8bef\u8bb0\u5f55',
                'verbose_name_plural': '\u9519\u8bef\u8bb0\u5f55',
            },
        ),
    ]
