# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_grouplearningplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplearningplan',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouplearningplan',
            name='unit',
        ),
        migrations.DeleteModel(
            name='GroupLearningPlan',
        ),
    ]
