# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-24 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_auto_20171116_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordinunit',
            name='detailed_meaning',
            field=models.TextField(default='', verbose_name='\u8be6\u7ec6\u89e3\u91ca'),
        ),
    ]
