# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-22 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0014_wordinunit_detailed_meaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '初次学习'), (2, '单元测试'), (3, '复习')], default=2, verbose_name='学习类型')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.WordUnit', verbose_name='单元')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学习任务',
                'verbose_name_plural': '学习任务',
            },
        ),
    ]
