# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0015_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningrecord',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='学习时长'),
        ),
    ]
