# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-08 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_learningrecord_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pronounciation_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='英式发音'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronounciation_us',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='美式发音'),
        ),
    ]
