# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import utils.time_util


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0019_auto_20181210_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='added_time',
            field=models.DateTimeField(default=utils.time_util.get_now, verbose_name='加入的时间'),
        ),
        migrations.AddField(
            model_name='learningplan',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='已完成'),
        ),
    ]
