# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-04 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import utils.time_util


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0020_auto_20190105_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='added_time',
            field=models.DateTimeField(default=utils.time_util.get_now, verbose_name='加入的时间'),
        ),
    ]
