# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-18 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord_group_usergroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '\u73ed\u7ea7', 'verbose_name_plural': '\u73ed\u7ea7'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': '\u5b66\u7c4d\u767b\u8bb0', 'verbose_name_plural': '\u5b66\u7c4d\u767b\u8bb0'},
        ),
    ]
