# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170818_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=200, upload_to='images/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
