# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 06:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170829_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7ec4\u7ec7\u540d')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='\u8be6\u7ec6\u63cf\u8ff0')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5b66\u6821',
                'verbose_name_plural': '\u5b66\u6821',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organization', verbose_name='\u5b66\u6821'),
        ),
    ]
