# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170912_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='role',
            field=models.IntegerField(choices=[(1, '\u5b66\u751f'), (2, '\u8001\u5e08'), (3, '\u7ba1\u7406\u5458')], default=1, verbose_name='\u7ec4\u5185\u7684\u89d2\u8272'),
        ),
    ]
