# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170912_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='\u662f\u4e0d\u662f\u5b66\u6821\u7ba1\u7406\u5458'),
        ),
    ]
