# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_group_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banner',
            field=models.TextField(default='', verbose_name='\u73ed\u7ea7\u516c\u544a'),
        ),
    ]
