# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-01 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usergroup_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='banner',
            field=models.TextField(default='', null=True, verbose_name='班级公告'),
        ),
    ]
