# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-01 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20181101_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='banner',
            field=models.TextField(blank=True, default='', null=True, verbose_name='班级公告'),
        ),
    ]
