# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-10 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import utils.time_util


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20181101_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=utils.time_util.get_now, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='create_time',
            field=models.DateTimeField(default=utils.time_util.get_now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='create_time',
            field=models.DateTimeField(default=utils.time_util.get_now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='join_time',
            field=models.DateField(default=utils.time_util.get_now, verbose_name='加入时间'),
        ),
    ]
