# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-24 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import utils.time_util


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20181210_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=30, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(default=utils.time_util.get_now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '短信验证码',
                'verbose_name_plural': '短信验证码',
            },
        ),
    ]
