# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-18 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0002_auto_20170817_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': '\u6d4b\u8bd5\u9898', 'verbose_name_plural': '\u6d4b\u8bd5\u9898'},
        ),
    ]
