# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testings', '0003_auto_20170818_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='state',
            field=models.CharField(choices=[('assigned', '\u672a\u7b54\u9898'), ('in_progress', '\u7b54\u9898\u4e2d'), ('finished', '\u5b8c\u6210')], default='assigned', max_length=15),
        ),
    ]
