# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_group_is_admin'),
        ('testings', '0004_auto_20170929_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserGroup', verbose_name='\u73ed\u7ea7')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7\u8003\u5377',
                'verbose_name_plural': '\u73ed\u7ea7\u8003\u5377',
            },
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': '\u8003\u5377', 'verbose_name_plural': '\u8003\u5377'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='group',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz_format',
            field=models.IntegerField(choices=[(0, '\u968f\u673a'), (1, '\u770b\u82f1\u6587\u9009\u4e2d\u6587'), (2, '\u770b\u4e2d\u6587\u9009\u82f1\u6587'), (3, '\u62fc\u5199')], default=0, verbose_name='\u6d4b\u8bd5\u5f62\u5f0f'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.WordInUnit', verbose_name='\u5355\u8bcd'),
        ),
        migrations.AddField(
            model_name='quizgroup',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testings.Quiz', verbose_name='\u8003\u5377'),
        ),
    ]
