# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0005_auto_20170929_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={'verbose_name': '\u7b54\u5377', 'verbose_name_plural': '\u7b54\u5377'},
        ),
    ]
