# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0006_auto_20170929_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='\u73ed\u7ea7'),
        ),
    ]
