# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_group_is_admin'),
        ('testings', '0007_auto_20170929_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='quizgroup',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='groups',
            field=models.ManyToManyField(to='users.Group', verbose_name='\u73ed\u7ea7'),
        ),
        migrations.DeleteModel(
            name='QuizGroup',
        ),
    ]
