# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-11 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0009_quizresult_correct_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestionresult',
            name='quiz_question',
        ),
        migrations.RemoveField(
            model_name='quizquestionresult',
            name='quiz_result',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='state',
        ),
        migrations.DeleteModel(
            name='QuizQuestionResult',
        ),
    ]
