# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0010_auto_20171011_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u516c\u5f00'),
        ),
    ]
