# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-21 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0011_quiz_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
