# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-10 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import utils.time_util


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0012_quiz_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='start_time',
            field=models.DateTimeField(default=utils.time_util.get_now, verbose_name='开始时间'),
        ),
    ]
